version: "3.8" 
services:
 mysql-container: # service name 
  image: mysql:8
  container_name: mysql-container
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: employee_db  // creates a db in the remote os(used by Docker)
  ports:
  - "3307:3306"
  restart: always // it ensures that docker container restarts when facing any problem
 spring-boot-container:
  build: ./
  container_name: spring-boot-container
  depends_on: 
   - mysql-container
  ports:
   - "8080:8080"
  restart: always
