FROM openjdk:17
COPY ./target/spring_boot_emp_rest_api-0.0.1-SNAPSHOT.jar .  // provides the path for the jar file of the project
CMD ["java", "-jar","spring_boot_emp_rest_api-0.0.1-SNAPSHOT.jar" ]  // runs the jar file when commanded in the docker-compose
